# goo4 Makefile
# Generated by CloudBees HiveVibe provisioning

APP_NAME := goo4
PORT := 8080
ECR_REPO := 189768267137.dkr.ecr.us-east-1.amazonaws.com/goo4-image
AWS_REGION := us-east-1
AWS_ACCOUNT_ID := 189768267137
IMAGE_TAG ?= latest
NAMESPACE := $(APP_NAME)

.PHONY: help
help: ## Show this help message
	@echo "goo4 - Development and Deployment"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'

# Local Development
.PHONY: run
run: ## Run application locally
	@echo "Starting $(APP_NAME) on http://localhost:$(PORT)"
	PORT=$(PORT) go run main.go

.PHONY: test
test: ## Run tests
	@echo "Running tests..."
	go test -v ./...

.PHONY: build
build: ## Build binary
	@echo "Building $(APP_NAME)..."
	go build -o $(APP_NAME) main.go
	@echo "✅ Binary created: ./$(APP_NAME)"

.PHONY: clean
clean: ## Remove built artifacts
	rm -f $(APP_NAME)

# Docker Operations
.PHONY: docker-build
docker-build: ## Build Docker image
	@echo "Building Docker image: $(APP_NAME):$(IMAGE_TAG)"
	docker build -t $(APP_NAME):$(IMAGE_TAG) .
	docker tag $(APP_NAME):$(IMAGE_TAG) $(APP_NAME):latest
	@echo "✅ Image built: $(APP_NAME):$(IMAGE_TAG)"

.PHONY: docker-run
docker-run: ## Run Docker image locally
	@echo "Running Docker container on http://localhost:$(PORT)"
	@echo "Press Ctrl+C to stop"
	docker run --rm -p $(PORT):$(PORT) -e PORT=$(PORT) $(APP_NAME):latest

.PHONY: docker-push
docker-push: docker-build ## Push Docker image to ECR
	@echo "Logging in to ECR..."
	@aws ecr get-login-password --region $(AWS_REGION) | \
		docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
	@echo "Tagging image for ECR..."
	docker tag $(APP_NAME):$(IMAGE_TAG) $(ECR_REPO):$(IMAGE_TAG)
	docker tag $(APP_NAME):$(IMAGE_TAG) $(ECR_REPO):latest
	@echo "Pushing to ECR..."
	docker push $(ECR_REPO):$(IMAGE_TAG)
	docker push $(ECR_REPO):latest
	@echo "✅ Image pushed to ECR: $(ECR_REPO):$(IMAGE_TAG)"

# Kubernetes Operations
.PHONY: k8s-deploy
k8s-deploy: ## Deploy to Kubernetes using Helm
	@echo "Deploying $(APP_NAME) to namespace $(NAMESPACE)..."
	helm upgrade --install $(APP_NAME) ./charts/$(APP_NAME) \
		--namespace $(NAMESPACE) \
		--set image.tag=$(IMAGE_TAG) \
		--wait
	@echo "✅ Deployed to Kubernetes"

.PHONY: k8s-status
k8s-status: ## Check Kubernetes deployment status
	@echo "Deployment status:"
	kubectl get pods,svc,ingress -n $(NAMESPACE)

.PHONY: k8s-logs
k8s-logs: ## Tail application logs
	@echo "Tailing logs for $(APP_NAME)..."
	kubectl logs -n $(NAMESPACE) -l app=$(APP_NAME) -f --tail=100

.PHONY: k8s-describe
k8s-describe: ## Describe Kubernetes resources
	@echo "Describing deployment..."
	kubectl describe deployment $(APP_NAME) -n $(NAMESPACE)

.PHONY: k8s-shell
k8s-shell: ## Open shell in running pod
	@kubectl exec -it -n $(NAMESPACE) $$(kubectl get pod -n $(NAMESPACE) -l app=$(APP_NAME) -o jsonpath='{.items[0].metadata.name}') -- /bin/sh

# Complete Workflow
.PHONY: all
all: test docker-build ## Run tests and build Docker image
	@echo "✅ $(APP_NAME) built and tested"

.PHONY: deploy
deploy: docker-push k8s-deploy ## Build, push, and deploy to Kubernetes
	@echo "✅ $(APP_NAME) deployed successfully"
	@echo ""
	@echo "Check status: make k8s-status"
	@echo "View logs:    make k8s-logs"
	@echo "URL:          https://$(APP_NAME).arch.beescloud.com"
